[package]
name = "slopos-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[[bin]]
name = "slopos-kernel"
path = "src/main.rs"

[features]
journal-replay-injection = []

[dependencies]
slopos-acpi = { path = "../crates/acpi" }
slopos-boot-protocol = { path = "../crates/boot-protocol" }
slopos-ebpf = { path = "../ebpf" }
slopos-ext4 = { path = "../crates/ext4" }
slopos-pci = { path = "../crates/pci" }
slopos-vfs = { path = "../crates/vfs" }
slopos-virtio = { path = "../crates/virtio" }
